# Generated by Django 3.1.5 on 2021-02-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('categories', models.CharField(blank=True, max_length=254, null=True)),
                ('id', models.CharField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('brand', models.CharField(max_length=254)),
                ('descriptions', models.TextField()),
                ('prices_amountMin', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imageURLs', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
