# Generated by Django 3.1.5 on 2021-03-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210322_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask_Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('topic', models.CharField(blank=True, max_length=254, null=True)),
                ('detail', models.TextField()),
            ],
        ),
    ]
